---
- name: Run Python scripts on APP server to create table/ganerate data/extract data
  hosts: appservers
  remote_user: centos

  tasks:

  - name: Run p_createtable.py
    ansible.builtin.script: /home/centos/ansible-test1/p_createtable.py
    args:
      executable: python3

  - name: Run p_gendata.py
    ansible.builtin.script: /home/centos/ansible-test1/p_gendata.py
    args:
      executable: python3

  - name: Run p_getdata.py
    ansible.builtin.script: /home/centos/ansible-test1/p_getdata.py
    args:
      executable: python3

  - name: Store generated csv in /tmp/.....
    ansible.builtin.fetch:
      src: /tmp/gathered_data.csv
      dest: /tmp/
      flat: yes


