---
- name: install python3, python3-pip, cx_oracle
  hosts: appservers
  remote_user: centos

  tasks:
  - name: install Python3 and Python3-pip
    yum:
      name: /home/centos/oracle-instantclient-basic-21.5.0.0.0-1.x86_64.rpm
      state: present
-   name: Install Oracle client sqlplus rpm from a local file
    yum:
      name: /home/centos/oracle-instantclient-sqlplus-21.5.0.0.0-1.x86_64.rpm
      state: present