---
- name: install python3, python3-pip, cx_oracle
  hosts: appservers
  become: true
  remote_user: centos

  tasks:
  - name: install Python3 and Python3-pip
    yum:
      name: python3, python3-pip
      state: present
